file_location: "indices.xml"
item_types: {'all' : 'index/names#',
          'periodical' : 'index/periodicals#',
          'publications' : 'pub/'}
header: {'name' : 'Digital Edition of Fernando Pessoa',
        'target' : 'http://www.pessoadigital.pt/',
        'contact' : 'Ulrike Henny-Krahmer <email>',
        'message' : 'Mentions in the digital edition of Fernando Pessoa',
        }
authority_urls: {'wikidata': 'https://www.wikidata.org/wiki/',
                'viaf': 'http://viaf.org/viaf/',
                'gnd': 'http://d-nb.info/gnd/'
                }